<?php

/**
 * Includes code for Custom Post Types
 * Generated by CPT UI
 */

function cptui_register_my_cpts() {

/**
 * Post Type: announcements.
 */

$labels = [
    "name" => __( "announcements", "tailpress" ),
    "singular_name" => __( "announcement", "tailpress" ),
    "menu_name" => __( "Announcements", "tailpress" ),
    "all_items" => __( "All announcements", "tailpress" ),
    "add_new" => __( "Add new", "tailpress" ),
    "add_new_item" => __( "Add new announcement", "tailpress" ),
    "edit_item" => __( "Edit announcement", "tailpress" ),
    "new_item" => __( "New announcement", "tailpress" ),
    "view_item" => __( "View announcement", "tailpress" ),
    "view_items" => __( "View announcements", "tailpress" ),
    "search_items" => __( "Search announcements", "tailpress" ),
    "not_found" => __( "No announcements found", "tailpress" ),
    "not_found_in_trash" => __( "No announcements found in trash", "tailpress" ),
    "parent" => __( "Parent announcement:", "tailpress" ),
    "featured_image" => __( "Featured image for this announcement", "tailpress" ),
    "set_featured_image" => __( "Set featured image for this announcement", "tailpress" ),
    "remove_featured_image" => __( "Remove featured image for this announcement", "tailpress" ),
    "use_featured_image" => __( "Use as featured image for this announcement", "tailpress" ),
    "archives" => __( "announcement archives", "tailpress" ),
    "insert_into_item" => __( "Insert into announcement", "tailpress" ),
    "uploaded_to_this_item" => __( "Upload to this announcement", "tailpress" ),
    "filter_items_list" => __( "Filter announcements list", "tailpress" ),
    "items_list_navigation" => __( "announcements list navigation", "tailpress" ),
    "items_list" => __( "announcements list", "tailpress" ),
    "attributes" => __( "announcements attributes", "tailpress" ),
    "name_admin_bar" => __( "announcement", "tailpress" ),
    "item_published" => __( "announcement published", "tailpress" ),
    "item_published_privately" => __( "announcement published privately.", "tailpress" ),
    "item_reverted_to_draft" => __( "announcement reverted to draft.", "tailpress" ),
    "item_scheduled" => __( "announcement scheduled", "tailpress" ),
    "item_updated" => __( "announcement updated.", "tailpress" ),
    "parent_item_colon" => __( "Parent announcement:", "tailpress" ),
];

$args = [
    "label" => __( "announcements", "tailpress" ),
    "labels" => $labels,
    "description" => "",
    "public" => true,
    "publicly_queryable" => true,
    "show_ui" => true,
    "show_in_rest" => true,
    "rest_base" => "",
    "rest_controller_class" => "WP_REST_Posts_Controller",
    "has_archive" => false,
    "show_in_menu" => true,
    "show_in_nav_menus" => true,
    "delete_with_user" => false,
    "exclude_from_search" => true,
    "capability_type" => "post",
    "map_meta_cap" => true,
    "hierarchical" => false,
    "rewrite" => [ "slug" => "announcements", "with_front" => true ],
    "query_var" => true,
    "menu_icon" => "dashicons-megaphone",
    "supports" => [ "title" ],
    "show_in_graphql" => false,
];

register_post_type( "announcements", $args );
}

add_action( 'init', 'cptui_register_my_cpts' );
